eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #,http://localhost:8762/eureka
   #register-with-eureka: false
  instance:
      prefer-ip-address: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761